# Generated by Django 3.2.13 on 2022-07-02 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('times', models.IntegerField(default=100)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2022, 7, 2, 12, 38, 15, 560913, tzinfo=utc))),
                ('is_login', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='VertificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=32)),
                ('vertificationCode', models.IntegerField()),
            ],
            options={
                'db_table': 'vtf_code',
            },
        ),
    ]
