# Generated by Django 3.2.13 on 2022-07-02 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 12, 39, 13, 474112, tzinfo=utc)),
        ),
    ]
