# Generated by Django 3.2.13 on 2022-07-04 03:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cd_use_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tc_use_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='td_use_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='te_use_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 3, 37, 8, 960859, tzinfo=utc)),
        ),
    ]
