# Generated by Django 3.2.13 on 2022-07-02 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=50)),
                ('upload_images', models.TextField()),
                ('result_images', models.TextField()),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2022, 7, 2, 12, 38, 15, 562907, tzinfo=utc))),
                ('type', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
