# Generated by Django 3.2.13 on 2022-07-04 03:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_history_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 3, 37, 8, 962855, tzinfo=utc)),
        ),
    ]
